# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movie_Collection' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Movie_Collection
  pod 'SDWebImage', '~>3.8'

end
